name: winter
description: "A framework built around get_it;"
version: 0.0.1

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  sqflite_common_ffi:
  path:
  path_provider:
  watch_it:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
